package com.bitnet

import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule

/**
 * Abstract base that mirrors the JS Turbo Module spec (NativeBitNet.ts).
 *
 * In a real New Architecture setup this would be auto-generated by
 * React Native codegen from the TS spec. We write it manually here so
 * the project compiles without needing to run the full codegen pipeline first.
 */
abstract class NativeBitNetSpec(context: ReactApplicationContext) :
    ReactContextBaseJavaModule(context) {

    abstract fun loadModel(
        modelPath: String,
        threads: Double,
        contextSize: Double,
        batchSize: Double,
        promise: Promise
    )

    abstract fun unloadModel(promise: Promise)
    abstract fun isModelLoaded(): Boolean

    abstract fun startGeneration(
        requestId: String,
        prompt: String,
        temperature: Double,
        topK: Double,
        topP: Double,
        maxTokens: Double,
        repetitionPenalty: Double,
        stopSequences: String,
        seed: Double,
        promise: Promise
    )

    abstract fun cancelGeneration(requestId: String)
    abstract fun tokenize(text: String, promise: Promise)
    abstract fun getDeviceInfo(): String
    abstract fun getBitNetVersion(): String
}
